<?xml version="1.0" encoding="UTF-8"?>
<descirption targetNamespace="http://jw.nju.edu.cn/wsdl"
             xmlns="http://www.w3.org/ns/wsdl"
             xmlns:xs="http://www.w3.org/2001/XMLSchema"
             xmlns:wsdlx="http://www.w3.org/ns/wsdl-extensions"
             xmlns:wsoap="http://www.w3.org/ns/wsdl/soap"
             xmlns:soap="http://www.w3.org/2003/05/soap-envelope"
             jw="http://jw.nju.edu.cn/schema"
>
    <documention>
        描述学生账号认证服务，包括邮箱认证和学号认证
    </documention>

    <types>

    </types>

    <interface name="emailAuthInterface">
        <operation name="emailAuth"
                   pattern="http://www.w3.org/ns/wsdl/in-out"
                   style="http://www.w3.org/ns/wsdl/style/iri"
                   wsdlx:safe="true">

            <fault name=""></fault>

            <!--类型还是元素-->
            <input messageLabel="In" element=""></input>
            <output messageLabel="Out" element=""></output>

            <outfault ref="" messageLabel="Out"></outfault>


        </operation>


    </interface>

    <binding name="emailAuthBinding" interface="emailAuthInterface"
             type="http://www.w3.org/ns/wsdl/soap"
             wsoap:protocol="http://www.w3.org/2003/05/soap/bindings/HTTP/">
        <operation ref="emailAuth" wsoap:mep="http://www.w3.org/2003/05/soap/mep/soap-response"/>



    </binding>

    <service name="emailAuthService"
             interface="emailAuthInterface">
        <endpoint name="emailAuthEndpoint"
                  binding="tns:reservationSOAPBinding"
                  address ="http://greath.example.com/2004/reservation"/>
    </service>



</descirption>