<?xml version="1.0" encoding="utf-8" ?>
<description targetNamespace="http://jw.nju.edu.cn/wsdl"
             xmlns:tns="http://jw.nju.edu.cn/wsdl"
             xmlns:jw="http://jw.nju.edu.cn/schema"
             xmlns="http://www.w3.org/ns/wsdl">
    <documentation>
        This document describes standard faults for use
        by Web services that process emailAuth.
    </documentation>
    <types>
        <xs:import xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   namespace="http://finance.example.com/CreditCardFaults/xsd"
                   schemaLocation=""/>

    </types>

    <interface name="studentIDAuthFault">
        <fault name="wrongStudentIDFormat" element="">
            <documention>Thrown when studentID format is wrong</documention>
        </fault>

        <fault name="wrongStudentIDAuth" element="">
            <documention>Thrown when studentID authentication is wrong</documention>
        </fault>
    </interface>


</description>