<?xml version="1.0" encoding="UTF-8"?>
<descirption targetNamespace="http://jw.nju.edu.cn/wsdl/studentAuth"
             xmlns:tns="http://jw.nju.edu.cn/wsdl"
             xmlns="http://www.w3.org/ns/wsdl"
             xmlns:xs="http://www.w3.org/2001/XMLSchema"
             xmlns:wsdlx="http://www.w3.org/ns/wsdl-extensions"
             xmlns:wsoap="http://www.w3.org/ns/wsdl/soap"
             xmlns:soap="http://www.w3.org/2003/05/soap-envelope"
             xmlns:jw="http://jw.nju.edu.cn/schema"
>
    <documention>
        describe student-authentication-service,including email authentication and studentID authentication
    </documention>

    <types>

        <xs:import xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   namespace="http://finance.example.com/CreditCardFaults/xsd"
                   schemaLocation="EmailAuth.xsd"/>
        <xs:import xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   namespace="http://finance.example.com/CreditCardFaults/xsd"
                   schemaLocation="StudentIDAuth.xsd"/>
    </types>

    <include location="EmailAuthFault.wsdl"/>

    <include location="StudentIDAuth.wsdl"/>

    <interface name="emailAuthInterface" extends="jw:emailAuthFault">
        <operation name="emailAuthOperation"
                   pattern="http://www.w3.org/ns/wsdl/in-out"
                   style="http://www.w3.org/ns/wsdl/style/iri"
                   wsdlx:safe="true">


            <input messageLabel="In" element="jw:emailAuthMsgType"/>
            <output messageLabel="Out" element="jw:studentToken"/>

            <infault ref="jw:invalidEmailAccountError" messageLabel="In"/>
            <outfault ref="jw:emailAuthError" messageLabel="Out"/>


        </operation>


    </interface>

    <interface name="studentIDAuthInterface" extends="jw:studentIDAuthFault">
        <operation name="studentIDAuthOperation"
                   pattern="http://www.w3.org/ns/wsdl/in-out"
                   style="http://www.w3.org/ns/wsdl/style/iri"
                   wsdlx:safe="true">


            <input messageLabel="In" element="jw:StudentIDAuthMsgType"/>
            <output messageLabel="Out" element="jw:studentToken"/>

            <infault ref="jw:invalidStudentIDError" messageLabel="In"/>
            <outfault ref="jw:studentIDNotExistError" messageLabel="Out"/>
            <outfault ref="jw:studentIDAuthError" messageLabel="Out"/>


        </operation>


    </interface>

    <binding name="emailAuthBinding" interface="tns:emailAuthInterface"
             type="http://www.w3.org/ns/wsdl/soap"
             wsoap:protocol="http://www.w3.org/2003/05/soap/bindings/HTTP/">
        <operation ref="emailAuthOperation" wsoap:mep="http://www.w3.org/2003/05/soap/mep/request-response"/>
        <fault ref="tns:invalidEmailAccountError"
               wsoap:code="soap:Sender"/>
        <fault ref="tns:emailAuthError"
               wsoap:code="soap:Sender"/>


    </binding>

    <binding name="studentIDAuthBinding" interface="tns:studentIDAuthInterface"
             type="http://www.w3.org/ns/wsdl/soap"
             wsoap:protocol="http://www.w3.org/2003/05/soap/bindings/HTTP/">
        <operation ref="studentIDAuthOperation" wsoap:mep="http://www.w3.org/2003/05/soap/mep/request-response"/>
        <fault ref="tns:invalidStudentIDError"
               wsoap:code="soap:Sender"/>
        <fault ref="tns:studentIDNotExistError"
               wsoap:code="soap:Sender"/>
        <fault ref="tns:studentIDAuthError"
               wsoap:code="soap:Sender"/>
    </binding>


    <service name="emailAuthService"
             interface="tns:emailAuthInterface">
        <endpoint name="emailAuthEndpoint"
                  binding="tns:emailAuthBinding"
                  address="http://jw.nju.edu.cn/emailAuth"/>
    </service>

    <service name="studentIDAuthService"
             interface="tns:studentIDAuthInterface">
        <endpoint name="studentIDAuthEndpoint"
                  binding="tns:studentIDAuthBinding"
                  address="http://jw.nju.edu.cn/StudentIDAuth"/>
    </service>


</descirption>